prometheus:
  enabled: false
  prometheusSpec:
    scrapeInterval: 10s
  service:
    type: NodePort

grafana:
  enabled: false
  serviceMonitor:
    interval: 10s
  service:
    type: NodePort

alertmanager:
  enabled: false

thanosRuler:
  enabled: false